####################
### KEYBINDINGSS ###
####################

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, F, fullscreen,
bind = $mainMod, R, exec, $menu
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod, C, exec, $calc
# bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, O, togglesplit, # dwindle
bind = $mainMod, W, exec, $browser

# refresh waybar
bind = $mainMod SHIFT, B, exec, ~/.dotfiles/waybar/.config/waybar/launch.sh

# lock screen
bind = $mainMod SHIFT, L, exec, hyprlock

# Screen brightness, using brightnessctl
bind = , XF86MonBrightnessUp, exec, changebrightness up
bind = , XF86MonBrightnessDown, exec, changebrightness down

# Volume control, using pamixer
binde = , XF86AudioRaiseVolume, exec, changevolume up
binde = , XF86AudioLowerVolume, exec, changevolume down 
bind = , XF86AudioMute, exec, changevolume mute   
bind = , XF86AudioMicMute, exec, pamixer --default-source -m  

# Media keys
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioStop, exec, playerctl stop
bind = , XF86AudioPrev, exec, playerctl previous
bind = , XF86AudioNext, exec, playerctl next

# Screenshots with grimblast
# Super+P save active window
# Super+Shift+P save area
bind = $mainMod, P, exec, grimblast --notify save screen
bind = $mainMod SHIFT, P, exec, grimblast --notify save area

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# special workspaces (scratchpad)
bind = $mainMod, S, togglespecialworkspace, term
bind = $mainMod, D, togglespecialworkspace, other
bind = $mainMod SHIFT, D, movetoworkspace, special:other

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bindm = $mainMod SHIFT, mouse:272, resizewindow
