##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

workspace = special:term, on-created-empty:kitty
# workspace = special:term,

windowrule {
    name = special-term
    match:workspace = special:term
    match:class = kitty

    float = true
    center = true
    size = (monitor_w*0.6) (monitor_h*0.6)
}

windowrule {
    name = browser
    match:class = firefox

    workspace = 2
}

windowrule {
    name = spotify_other
    match:class = spotify

    float = true
    size = (monitor_w*0.6) (monitor_h*0.6)
    move = 80 90
}

windowrule {
    name = blueman
    match:class = blueman-manager
    
    float = true
    center = true
    size = 600 400
}

windowrule {
    name = default-thing
    match:class = .*

    suppress_event = maximize
}
# windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
